### ISSUE TITLE
Can't Uninstall 

### ISSUE THREAD

**Issue by dominikandreas** [Gainedge/BetterExplorer#124]
Trying to uninstall via "Programs and Features" only opens the installation dialog. How do I uninstall this?

**Comment by DimitarCC** [comment]
After installation dialog is open on next step there is remove.

**Comment by yosagi** [comment]
I've installed Beter Explorer 2020.03.15.1304, and I could not find 'remove' button or checkbox or something like that on the installer wizard. The first three screen I see on installer wizard are:
1. Welcome to the Better Explorer Setup Wizard  (a Next button)
2. Read the Gainedge.org License Terms (Print, Back, Next buttons and an accept checkbox)
3. Choose a file location  ( Broese..., Back, Next buttons and a Line edit)
How can I uninstall it.

**Comment by yosagi** [comment]
I could uninstall it by  launching BetterExplorer.exe stored under C:\ProgramData\Caphyon\Advanced Installer\{3B384425-3607-4A80-BC5E-3E77BDEA38FE} directry.
