### ISSUE TITLE
Can not find path or internet address

### ISSUE THREAD

**Issue by NorikatsuTanaka** [Gainedge/BetterExplorer#125]
When click file icon to preview window, this error is appeared.
![cna not find pass](https://user-images.githubusercontent.com/48576320/54404525-1eea4400-4717-11e9-8b21-0aa41334751f.jpg)

**Comment by JaykeBird** [comment]
This seems to suggest that the preview window is using the wrong encoding to read the filepath string (i.e. the filepath string should be read as UTF-8, but is instead being read as ASCII or something)

**Comment by DimitarCC** [comment]
@NorikatsuTanaka  I will check it however it is good to specify at what system you run Better Explorer and What version you are running.

**Comment by NorikatsuTanaka** [comment]
PC system is;
Windows 10 Pro
Intel Core i5-6500 64bit
Better explorer is;
Ver 2018.06.06.6 RC 64bit

Hoping above helps you a lot!

**Comment by NorikatsuTanaka** [comment]
I could uninstall 2018.06.06.06RC by tool you proposed, and could install trial version.
Thank you for your advice.
However issue of this thread #125 is happened again.
I don't know what's is issues on my PC...

**Comment by DimitarCC** [comment]
Well yes that issue will be hard to figure out. I may try to run some tests to see will i be able to get that issue on my side.

**Comment by JaykeBird** [comment]
I can attempt to assist by setting my Windows to Japanese and seeing what I can do. it'll be a short bit though

**Comment by DimitarCC** [comment]
@JaykeBird Yes if is possible it will be nice to test. However you will need to use the latest source since i made some fixes there......

**Comment by DimitarCC** [comment]
@NorikatsuTanaka  here is new installer with possible fix. So you may test it as well.


[BetterExplorer-v2019.03.22.1.zip](https://github.com/Gainedge/BetterExplorer/files/2999380/BetterExplorer-v2019.03.22.1.zip)

**Comment by DimitarCC** [comment]
No info what is the status so I'm closing this.
