### ISSUE TITLE
Can't Open

### ISSUE THREAD

**Issue by YoiBoi86** [Gainedge/BetterExplorer#127]
I clicked exit once. Now it doesn't open at all. Nada. Not even in the background. I tried TaskMGR. That didn't work. Nothing works.

**Comment by DimitarCC** [comment]
Please give me more info about this. What version of Better Explorer you are using, what is your system and did you clicked on the exit in File menu or you just clicked on the "X" button?

**Comment by YoiBoi86** [comment]
I don't know what version, pretty recent. And, I clicked File, Exit.

**Comment by DimitarCC** [comment]
well you can check in the file menu -> information tab. There is written the version.
And you may try  the version posted at #125 https://github.com/Gainedge/BetterExplorer/files/2999380/BetterExplorer-v2019.03.22.1.zip

**Comment by YoiBoi86** [comment]
I can't check the file menu since it won't open but Programs and Features says it's version "2018.6.6.6" I cannot reinstall at the moment because I will need administrator permission.

**Comment by DimitarCC** [comment]
@YoiBoi86 Your version seems to be too old. I recommend using the one i referred above.

**Comment by Kai78** [comment]
Got same issue here with version 2018.06.06.6 RC. 
Would be a great alternative to Windows Explorer.

**Comment by DimitarCC** [comment]
> 
> 
> Got same issue here with version 2018.06.06.6 RC.
> Would be a great alternative to Windows Explorer.

Use the version referenced from me above. The one you use is too old.

**Comment by DimitarCC** [comment]
Well no info from moths. So i close this.
