### ISSUE TITLE
Please add mode view files in custom position.

### ISSUE THREAD

**Issue by korenevskiy** [Gainedge/BetterExplorer#128]
I needed to sort files (pictures) manually by color. Sort by rainbow color.
I dragged 80 files with the mouse on the canvas inside the folder.
Initially, red, yellow in one corner, green, blue in another corner, feliolet, gray in the third corner.
I needed to sort them similarly to the desktop icons. But how can I do this with your explorer?

**Comment by DimitarCC** [comment]
How do you do it in Windows Explorer?

**Comment by DimitarCC** [comment]
No info from the reporter
