### ISSUE TITLE
Feature request - Double click an empty space for parent folder

### ISSUE THREAD

**Issue by Fuzen777** [Gainedge/BetterExplorer#131]
Coming from XYplorer, QTTabBar and Clover to only mention these, I noticed the absence of that extremely useful functionality. 

The title pretty much describes it all – click an empty space in a folder and it would go to the parent folder. It’s simple yet it really smoothes workflows. Could you perhaps look into adding such a feature ?

**Comment by DimitarCC** [comment]
Hello and thank you for using Better Explorer.
I will look at that functionality and will add it as an option.
But let me ask you what version you are testing right now?
In the upcoming days there will be a new release with many changes (depending on what version you testing now). Please note that the new version will ONLY support Windows 10.
If you have any questions please ask.

**Comment by Fuzen777** [comment]
I’m using 2018.06.06.6 RC, the one downloaded from the main site. I was testing a few alternatives to File Explorer in batch… so I hadn’t realized that it was quite so old, actually. Should I build from the repository instead ?

In any case, Better Explorer really caught my interest, and I’m curious to see how it will evolve in the future.

**Comment by DimitarCC** [comment]
Well it is tricky to build it yourself. Ofcource you can try if you like. But i can provide you with testing build if you like.

**Comment by Fuzen777** [comment]
If it is not too much trouble for you, that would be great. Otherwise, I’ll just try my hand with the instructions you provided.

**Comment by DimitarCC** [comment]
OK. Look again at the main site download page. There is new version there 2020.03.15.1304 RC.
Please try it and let me know is it working. Keep in mind it is still RC so it may have some issues.

**Comment by DimitarCC** [comment]
Its done. It will be available in next update.
