### ISSUE TITLE
PInvoke Unbalanced Stack in SHCreateItemFromIDList

### ISSUE THREAD

**Issue by JaykeBird** [Gainedge/BetterExplorer#140]
Hello! It's been a while! :D Wanted to try and see if I could run the latest build and poke around a bit.

I receive the following message while attempting to debug. I first see it when it's attempting to load a thumbnail for the current tab, but it occurs elsewhere too (I can share stack traces if needed).

```
Managed Debugging Assistant 'PInvokeStackImbalance' 
  Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'BExplorerShell!ThumbnailGenerator.WindowsThumbnailProvider::SHCreateItemFromIDList' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
```

Looking at SHCreateItemFromIDList, its definition seems to match what is expected [according to Microsoft's documentation](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-shcreateitemfromidlist), so I'm a bit confused as to what the issue is here. Is this just a non-issue or is there something that needs to be done here?

When the main window appears, none of the items in the shell view have thumbnails. I wonder if this is related to that too somehow?

Either way, I'm going to continue looking around at the code as well!

**Comment by DimitarCC** [comment]
Hey @JaykeBird 
This could be also because of the mistake of build configuration of the project. You have to run it at AnyCPU configuration so everything to works well.
If it still gives you that error please let me know at what version of windows you run it so to be able to find the problem.
The problem with missing thumbnails is definitely the problem with build configuration. Please set the solution build configuration to AnyCPU and try again.

**Comment by JaykeBird** [comment]
Yep, changing the build configuration to AnyCPU helped a lot! Silly me lol. Is there a reason for having the "Mixed Platforms" configuration? Glad I can get it going now though!

**Comment by DimitarCC** [comment]
@JaykeBird Well the mixed platform setting is generally set up by Visual Studio itself. Actually there is no such a setting set up on purpose ;)
