### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by r3sus** [Gainedge/BetterExplorer#143]
Hello.

I'm following Readme and trying to build BE with [latest SharpDevelop](https://sourceforge.net/projects/sharpdevelop/). I get this error on opening .sln:

<details> <summary>Error</summary>

Error loading C:\Users\1\source\repos\BetterExplorer\BExplorer\BetterExplorer\BetterExplorer.csproj:
The tools version "12.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\Users\1\source\repos\BetterExplorer\BExplorer\BetterExplorer\BetterExplorer.csproj

</details>

I've installed MSBuild Tools 2013 as suggested [here](https://stackoverflow.com/questions/32417901/the-tools-version-12-0-is-unrecognized-available-tools-versions-are-2-0-3) and [there](https://stackoverflow.com/questions/22015916/sharpdevelop-error-the-tools-version-12-0-is-unrecognized).

Now, I get even more errors.

<details> <summary>Error type 2</summary>

Error loading C:\Users\1\source\repos\BetterExplorer\BExplorer\BetterExplorer\BetterExplorer.csproj:
A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "10.0.10240.0" instead of a number, in condition "'$(UseOSWinMdReferences)' == '' and ('$(TargetPlatformWinMDLocation)' == '' and '$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0')".  C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets

</details>

I didn't tried VS 2013 Express, as I've latest VS Community installed and afraid of conflicts. Or it is safe? 

I'm not such interested in building it myself, as to try latest build. Noteworthy, Readme states:
> You can also download a test build from our website.

Thanks for your work.

**Comment by DimitarCC** [comment]
@r3sus  The build instructions are outdated now. The only way to build BE is with Visual Studio 2019.
I will correct the readme!

**Comment by r3sus** [comment]
Thanks! That was the first I tried and got the next message on opening .sln. So I thought I've to follow Readme. Now I successfully compiled it. (Powershell still don't works for me)
<details> <summary>Message</summary>

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Better Explorer AI Setup, "C:\Users\1\Source\Repos\BetterExplorer\Better Explorer AI Setup\Better Explorer AI Setup.aiproj"


No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - Solution Items, "Solution Items"
	 - BExplorer, "C:\Users\1\Source\Repos\BetterExplorer\BExplorer.sln"

from `UpgradeLog.htm`:
The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660952&projecttype=840C416C-B8F3-42BC-B0DD-F6BB14C9F8CB

</details>

I've got 68 warnings during compiling. I'm sure these are known, but just in case I'll include them:
<details> <summary>Compiling warnings</summary>

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning | CS0618 | 'ShellView.RedrawWindow()' is obsolete: 'Contains No Code' | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 2006 | Active
Warning | CS0108 | 'Axis.BorderBrush' hides inherited member 'Control.BorderBrush'. Use the   new keyword if hiding was intended. | RateBar | C:\Users\1\Source\Repos\BetterExplorer\Progress\Common\Axis.cs | 29 | Active
Warning | CS0067 | The event 'RateBase.CaptionChanged' is never used | RateBar | C:\Users\1\Source\Repos\BetterExplorer\Progress\Common\RateBase.cs | 81 | Active
Warning | CS1573 | Parameter 'width' has no matching param tag in the XML comment for   'Defaults.ToNativeColumn(Collumns, bool, int)' (but other parameters do) | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\Defaults.cs | 365 | Active
Warning | CS0219 | The variable 'i' is assigned but its value is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\Extensions.cs | 745 | Active
Warning | CS0414 | The field 'FileOperationDialog.IsShown' is assigned but its value is   never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\FileOperation\FileOperationDialog.xaml.cs | 14 | Active
Warning | CS1573 | Parameter 'dialog' has no matching param tag in the XML comment for   'IIFileOperation.IIFileOperation(IFileOperationProgressSink, IntPtr, bool,   IOperationsProgressDialog)' (but other parameters do) | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\FileOperation\IIFileOperation.cs | 66 | Active
Warning | CS0219 | The variable 'h' is assigned but its value is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\Interop\NativeWindowListener.cs | 31 | Active
Warning | CS0067 | The event 'ShellTreeView.AfterSelect' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 59 | Active
Warning | CS0414 | The field 'ShellTreeView._SearchingForFolders' is assigned but its value   is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 69 | Active
Warning | CS0169 | The field 'ShellTreeView.folderImageListIndex' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 74 | Active
Warning | CS0169 | The field 'ShellTreeView.imagesThread' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 80 | Active
Warning | CS0169 | The field 'ShellTreeView.childsThread' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 81 | Active
Warning | CS0414 | The field 'ShellTreeView._IsNavigate' is assigned but its value is never   used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 83 | Active
Warning | CS0414 | The field 'ShellTreeView._EmptyItemString' is assigned but its value is   never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 84 | Active
Warning | CS0414 | The field 'ShellTreeView._AcceptSelection' is assigned but its value is   never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeView.xaml.cs | 85 | Active
Warning | CS0067 | The event 'ShellTreeViewEx.AfterSelect' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellTreeViewEx.cs | 42 | Active
Warning | CS0067 | The event 'ShellView.OnLVScroll' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 269 | Active
Warning | CS0414 | The field 'ShellView._HasScrollbar' is assigned but its value is never   used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 336 | Active
Warning | CS0649 | Field 'ShellView._EditorSubclass' is never assigned to, and will always   have its default value null | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 500 | Active
Warning | CS0162 | Unreachable code detected | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 1894 | Active
Warning | CS0618 | 'ShellView.RedrawWindow()' is obsolete: 'Contains No Code' | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 2019 | Active
Warning | CS0169 | The field 'ShellView._IsDDOpen' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 2074 | Active
Warning | CS0168 | The variable 'ex' is declared but never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 2729 | Active
Warning | CS0219 | The variable 'loopCondition' is assigned but its value is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 3072 | Active
Warning | CS0169 | The field 'ShellView._IsAutoScrool' is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 4575 | Active
Warning | CS0168 | The variable 'ex' is declared but never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 4744 | Active
Warning | CS0168 | The variable 'ex' is declared but never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 4821 | Active
Warning | CS0219 | The variable 't' is assigned but its value is never used | Shell | C:\Users\1\Source\Repos\BetterExplorer\Shell\ShellViewEx.cs | 4831 | Active
Warning | CS0168 | The variable 'e' is declared but never used | BetterExplorerControls | C:\Users\1\Source\Repos\BetterExplorer\WpfControlLibrary1\AirspacePopup.cs | 110 | Active
Warning | CS0067 | The event 'DetailsPane.PropertyChanged' is never used | BetterExplorerControls | C:\Users\1\Source\Repos\BetterExplorer\WpfControlLibrary1\PreviewPane.xaml.cs | 18 | Active
Warning | CS0067 | The event 'ProcessInterface.OnProcessInput' is never used | ConsoleControl | C:\Users\1\Source\Repos\BetterExplorer\ConsoleControl\Process   Helper\ProcessInterface.cs | 112 | Active
Warning | CS0618 | 'TabControl.OnCoerceAllowAddNewCallback(object)' is obsolete: 'Exactly   the same as OnCoerceAllowDeleteCallback(...)' | Wpf.TabControl | C:\Users\1\Source\Repos\BetterExplorer\TabControl\TabControl.cs | 214 | Active
Warning | CS0618 | 'TabControl.OnCoerceAllowDeleteCallback(object)' is obsolete: 'Exactly   the same as OnCoerceAllowAddNewCallback(...)' | Wpf.TabControl | C:\Users\1\Source\Repos\BetterExplorer\TabControl\TabControl.cs | 215 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | Wpf.TabControl | C:\Users\1\Source\Repos\BetterExplorer\TabControl\TabControl.cs | 303 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | Wpf.TabControl | C:\Users\1\Source\Repos\BetterExplorer\TabControl\TabControl.cs | 321 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | Wpf.TabControl | C:\Users\1\Source\Repos\BetterExplorer\TabControl\TabControl.cs | 348 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | Wpf.TabControl | C:\Users\1\Source\Repos\BetterExplorer\TabControl\TabControl.cs | 390 | Active
Warning | CS0618 | 'NotificationActivator' is obsolete: 'You can now subscribe to activation   by simpy using the ToastNotificationManagerCompat.OnActivated event. We   recommend deleting your NotificationActivator and switching to using the   event.' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\Api\ToastNotifications\BetterExplorerNotificationActivator.cs | 11 | Active
Warning | CS0618 | 'NotificationActivator' is obsolete: 'You can now subscribe to activation   by simpy using the ToastNotificationManagerCompat.OnActivated event. We   recommend deleting your NotificationActivator and switching to using the   event.' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\Api\ToastNotifications\BetterExplorerNotificationActivator.cs | 13 | Active
Warning | CS0618 | 'DesktopNotificationManagerCompat' is obsolete: 'We recommend switching   to the new ToastNotificationManagerCompat. For Win32 apps, it no longer   requires a Start menu shortcut, and activation now uses a straightforward   event handler (no NotificationActivator class and COM GUIDs needed)!' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\App.xaml.cs | 161 | Active
Warning | CS0618 | 'DesktopNotificationManagerCompat' is obsolete: 'We recommend switching   to the new ToastNotificationManagerCompat. For Win32 apps, it no longer   requires a Start menu shortcut, and activation now uses a straightforward   event handler (no NotificationActivator class and COM GUIDs needed)!' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\App.xaml.cs | 162 | Active
Warning | CS0618 | 'WizardControl.Cancelled' is obsolete: 'The Cancelled event is obsolete   in version 1.2; use the Cancelling event instead.' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\ArchiveView\ArchiveCreateWizard.Designer.cs | 97 | Active
Warning | CS1762 | A reference was created to embedded interop assembly 'Interop.Shell32,   Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because of an indirect   reference to that assembly created by assembly 'BetterExplorerControls,   Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Consider changing the   'Embed Interop Types' property on either assembly. | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\CSC | 1 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 2887 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 2924 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 2972 | Active
Warning | CS0618 | 'TabControl.IsInTabDragDrop' is obsolete: 'Assigned values but not used' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 2978 | Active
Warning | CS0162 | Unreachable code detected | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 3246 | Active
Warning | CS0618 | 'TabControl.IsSelectionHandled' is obsolete: 'Assigned but not used' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 4075 | Active
Warning | CS0618 | 'TabControl.IsSelectionHandled' is obsolete: 'Assigned but not used' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 4081 | Active
Warning | CS0414 | The field 'MainWindow._ScrollOldValue' is assigned but its value is never   used | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 4224 | Active
Warning | CS0414 | The field 'MainWindow._IsScrollingManually' is assigned but its value is   never used | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\MainWindow.xaml.cs | 4225 | Active
Warning | CS0414 | The field 'MainWindow._IsCheckUpdateFromTimer' is assigned but its value   is never used | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\_MainWindow\MainWindow_Updating.cs | 16 | Active
Warning | CS0414 | The field 'MainWindow._IsUpdateNotificationMessageBoxShown' is assigned   but its value is never used | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\_MainWindow\MainWindow_Updating.cs | 17 | Active
Warning | CS0618 | 'DesktopNotificationManagerCompat' is obsolete: 'We recommend switching   to the new ToastNotificationManagerCompat. For Win32 apps, it no longer   requires a Start menu shortcut, and activation now uses a straightforward   event handler (no NotificationActivator class and COM GUIDs needed)!' | BetterExplorer | C:\Users\1\Source\Repos\BetterExplorer\BExplorer\BetterExplorer\_MainWindow\MainWindow_Updating.cs | 82 | Active
Warning |   | Could not find rule set file "..\Fluent.Ribbon.ruleset". | Fluent.Ribbon.NET 4.6 |  
Warning |   | Could not find rule set file "..\Fluent.Ribbon.ruleset". | Fluent.Ribbon.NET 4.6 |  
Warning |   | Could not find rule set file "..\Fluent.Ribbon.ruleset". | Fluent.Ribbon.NET 4.6 |  
Warning |   | Could not resolve this reference. Could not locate the assembly   "Windows.Data". Check to make sure the assembly exists on disk. If   this reference is required by your code, you may get compilation errors. | BetterExplorer |   |  
Warning |   | Found conflicts between different versions of the same dependent   assembly. Please set the "AutoGenerateBindingRedirects" property to   true in the project file. For more information, see   http://go.microsoft.com/fwlink/?LinkId=294190. | BetterExplorer |   |  
Warning |   | Found conflicts between different versions of "Newtonsoft.Json"   that could not be resolved.  These   reference conflicts are listed in the build log when log verbosity is set to   detailed. | BetterExplorer |   |  
Warning |   | No way to resolve conflict between "Zlib.Portable, Version=1.11.0.0,   Culture=neutral, PublicKeyToken=431cba815f6a8b5b" and   "Zlib.Portable, Version=1.11.0.0, Culture=neutral,   PublicKeyToken=null". Choosing "Zlib.Portable, Version=1.11.0.0,   Culture=neutral, PublicKeyToken=431cba815f6a8b5b" arbitrarily. | BetterExplorer |   |  
Warning |   | The explicit binding redirect on "System.Net.Http, Culture=neutral,   PublicKeyToken=b03f5f7f11d50a3a" conflicts with an autogenerated binding   redirect. Consider removing it from the application configuration file or   disabling autogenerated binding redirects. The build will replace it with:   "<bindingRedirect oldVersion="0.0.0.0-4.2.0.0"   newVersion="4.2.0.0"   xmlns="urn:schemas-microsoft-com:asm.v1" />". | BetterExplorer |   |  
Warning |   | The referenced component 'Windows.Data' could not be found. | BetterExplorer |   |  
Warning |   | The referenced project 'Shell' is targeting a higher framework version   (4.7.2) than this project’s current target framework version (4.6). This may   lead to build failures if types from assemblies outside this project’s target   framework are used by any project in the dependency chain. | TestProject |   |  

Detected package downgrade:   Newtonsoft.Json from 12.0.3 to 11.0.2. Reference the package directly from   the project to select a different version. BetterExplorer -> Google.Apis.Drive.v2   1.51.0.2265 -> Google.Apis 1.51.0 -> Google.Apis.Core 1.51.0 ->   Newtonsoft.Json (>= 12.0.3) 
BetterExplorer -> Newtonsoft.Json (>=   11.0.2) 

</details>
